### PR TITLE
Upgrade Setup.hs

### PR DESCRIPTION
**Pull request by jystic**
Needs this for 7.10

### CODE REVIEW

**Comment by nhibberd** [comment]
You will need to change the build scripts to look in gen not autogen for version.txt

**Comment by nhibberd** [comment]
And maybe add gen to gitignore

**Comment by jystic** [comment]
lol, did you even `Setup.hs` before pushing it, just noticed this haha:
```
dist/setup/setup.hs:73:38: Not in scope: ‘isDigit’
```

**Comment by jystic** [comment]
This should be good to go, many more passing mismi builds now due to the `bin/ci.cabal` change

**Comment by nhibberd** [comment]
:+1:

**Pull request merged**
