### PR TITLE
Fix testAWS

### PR DESCRIPTION
**Pull request by charleso**
/cc @EduardSergeev @jystic

### CODE REVIEW

**Comment by charleso** [comment]
https://github.com/search?utf8=%E2%9C%93&q=user%3Aambiata+testAWS&type=Code&ref=searchresults

**Comment by jystic** [comment]
:currency_exchange:

**Comment by EduardSergeev** [comment]
:+1:

**Comment by jystic** [comment]
:violin: :waxing_gibbous_moon: :violin:

**Pull request merged**
