### PR TITLE
Upgrade amazonka to 1.3.6

### PR DESCRIPTION
**Pull request by olorin**
For whenever we're ready to do this.

### CODE REVIEW

**Comment by nhibberd** [comment]
I might raise an issue of things to do before this goes in, not many now

**Comment by olorin** [comment]
Sounds good, thanks.

**Comment by nhibberd** [comment]
Fixes #220

**Comment by nhibberd** [comment]
@olorin Feel free to rebase and merge this now

**Comment by nhibberd** [comment]
Think might have missed elb and emr, will fix up tomorrow

**Comment by olorin** [comment]
Derp, sorry. #268

**Pull request merged**
