### PR TITLE
Topic/upgrade all

### PR DESCRIPTION
**Pull request by erikd-ambiata**
This is a pretty big PR. Main thing is to update some critical libraries:
 * http-conduit/http-client/http-client-tls etc (new versions have better error handling).
 * amazonka (need to update this to use the above, required some code changes due to changed constructors and type signatures).
 * connection == 0.2.8 (I have independently validated that this fixes the socket leak problems with 0.2.6 and 0.2.7).

There are 5 small commits and then one huge one with all the cabal and lock file version changes.

Pretty sure this does not fix the s3 downlaod issue, but gets us to a good position to raise an issue with Snoyman.

! @nhibberd @olorin

### CODE REVIEW

**Comment by erikd-ambiata** [comment]
Lock files are not quite right yet.

**Comment by tmcgilchrist** [comment]
Bump

**Comment by nhibberd** [comment]
There needs to be some compatibility testing done with this, there is some breaking internal APIs

**Comment by erikd-ambiata** [comment]
@nhibberd What needs to be tested?

**Comment by olorin** [comment]
@nhibberd ping, would be good to get this merged or closed.

**Comment by nhibberd** [comment]
> @nhibberd ping, would be good to get this merged or closed.

Has been discussed offline, this is good to go as soon as its been tested

**Comment by erikd-ambiata** [comment]
@nhibberd What would you want in the way of testing?

**Comment by erikd-ambiata** [comment]
Off line reply: make hydra and manor build with this version of mismi.

**Comment by erikd-ambiata** [comment]
Finally figured out a problem with this. The updated Amazonka in this PR, ends up depending on `http-client == 0.5.*` whereas all of our Ambiata stuff has `http-client < 0.5`.

Probably worth shelving this until a new version of Amazonka comes out (https://github.com/brendanhay/amazonka/issues/406#issuecomment-331832806) which may actually be soon.

**Comment by phickey** [comment]
@erikd-ambiata is it worth revisiting this work now that Amazonka 1.5.0 exists - which has an explicit dependency for `http-conduit (>=2.2 && <3)` which in turn has a `http-client (==0.5.*)` dependency?

**Comment by erikd-ambiata** [comment]
Yes, very definitely worth revisiting this!!!!!

**Comment by nhibberd** [comment]
Trying this with a fork now

**Comment by charleso** [comment]
@nhibberd Should I close this in favour of https://github.com/ambiata/mismi/pull/384 or it worth trying to make this pass as well?

**Comment by charleso** [comment]
Closing this, https://github.com/ambiata/mismi/pull/384 is now green

**Pull request closed without merging**
