### PR TITLE
Deprecate `s3 read`

### PR DESCRIPTION
**Pull request by olorin**
Redo of #340.

! @nhibberd @markhibberd
/jury approved @tmcgilchrist @erikd-ambiata

### CODE REVIEW

**Comment by tmcgilchrist** [comment]
Worth mentioning what it's deprecated in favour of?

**Comment by olorin** [comment]
> Worth mentioning what it's deprecated in favour of?

Done.

**Comment by tmcgilchrist** [comment]
👍

**Comment by erikd-ambiata** [comment]
:+1:

**Comment by nhibberd** [comment]
No thoughts on the deprecation, but if its going to stay in the cli why don't we change the semantics to match cat?

**Comment by olorin** [comment]
> No thoughts on the deprecation, but if its going to stay in the cli why don't we change the semantics to match cat?

Don't want to break anything - some tools might be relying on the old behaviour. That was my reasoning anyway.

**Comment by HuwCampbell** [comment]
Could just put it in a separate `subparser` with an `internal` mod.

**Comment by olorin** [comment]
@HuwCampbell what would that get us?

@nhibberd @markhibberd okay to merge?

**Comment by olorin** [comment]
Going to push this through if there are no objections.

**Comment by HuwCampbell** [comment]
It wouldn't change to much, just hide it from the usage text while still allowing older scripts to use it. Pretty similar to marking as deprecated.

**Comment by olorin** [comment]
@HuwCampbell right yep, sounds handy. Will do.

**Comment by HuwCampbell** [comment]
I don't think this is right @olorin,

That internal is applied to the whole set of commands (the (<>) affects all of them) and nothing will be visible. It would need to be in a separate `subparser` as well.

**Pull request merged**
