### PR TITLE
HOLD - Upgrading to amazonka-1.3.3.1

### LINKED ISSUE #220: List needs to support 'STANDARD_IA'
```
s3 ls s3://<file>
[SerisalizeError] {
  service = S3
  status  = 200 OK
  message = Failed reading: Failure parsing ObjectStorageClass from value: 'standard_ia'. Accepted values: GLACIER, REDUCED_REDUNDANCY, STANDARD
}
```

### PR DESCRIPTION
**Pull request by nhibberd**
Needs a more thorough discuss (https://github.com/brendanhay/amazonka/compare/1.3.2.1...1.3.3.1)

Fixes #220 
ambiata/bucket#13

### CODE REVIEW

**Comment by nhibberd** [comment]
Main upgrades that will affect mismi
- 100 continues on `putBody` requests
- `GetBucketLogging` fix
- `ListObjects` for `STANDARD_IA` fix
- new libraries - `waf` / `kinesis-firehose` / `inspector` / `marketplace-analytics` / `iot`

**Comment by charleso** [comment]
:+1:

**Comment by EduardSergeev** [comment]
:+1:

**Comment by nhibberd** [comment]
If someone wants to go ahead with this, current plan is to lock down stable versions of juice/eagle/etc in prod. Upgrade this and unlock versions for certain environments going forward

**Comment by nhibberd** [comment]
NB - this is on hold until twine changes are rolled through, and multipart copy is done

**Comment by nhibberd** [comment]
As discussed on #258, will close this for now

**Pull request closed without merging**
