### PR TITLE
Adding an s3 cat command

### PR DESCRIPTION
**Pull request by nhibberd**
@EduardSergeev @charleso

### CODE REVIEW

**Comment by EduardSergeev** [comment]
Extend [cli test](https://github.com/ambiata/mismi/blob/master/mismi-s3/test/cli/work/run) with `cat` command?
Is it basically stream version of `read`? For large files?

**Comment by nhibberd** [comment]
Added a test to ensure compatibility with `read`, and yeah its for streaming large files

**Comment by EduardSergeev** [comment]
:+1:

**Comment by charleso** [comment]
:+1:

**Pull request merged**
