### PR TITLE
Retry on missing ETags

### PR DESCRIPTION
**Pull request by olorin**
! @nhibberd @erikd-ambiata @charleso 
/jury approved @erikd-ambiata

### CODE REVIEW

**Comment by erikd-ambiata** [comment]
The failure to build you are seeing is due to a corrupted mafia build cache.

**Comment by olorin** [comment]
Yeah I figured that was probably it - is there a procedure to fix that?

**Comment by charleso** [comment]
Lazy question, when is the etag missing?

**Comment by olorin** [comment]
> Lazy question, when is the etag missing?

Dunno. @nhibberd ^?

**Comment by nhibberd** [comment]
> > Lazy question, when is the etag missing?

> Dunno. @nhibberd ^?

From memory it is mandatory on the response, it is sometimes missing but is just an invariant

**Comment by olorin** [comment]
Everyone okay with this?

**Comment by erikd-ambiata** [comment]
👍

**Pull request merged**
