### PR TITLE
Dial back the concurrency on multipartUpload.

### PR DESCRIPTION
**Pull request by tmcgilchrist**
! @erikd-ambiata @nhibberd 

Similar to the fix from here: https://github.com/ambiata/mismi/pull/362

NOTE I've not tested the impact on the upload speeds yet.
/jury approved @nhibberd

### CODE REVIEW

**Comment by erikd-ambiata** [comment]
Yep, seems sane. Would be good to validate the the speed is the same or better.

👍

**Comment by nhibberd** [comment]
Can we update https://github.com/ambiata/mismi/blob/master/mismi-s3/doc/benchmarks.md as part of the validation

**Comment by erikd-ambiata** [comment]
Compiled separate binaries with and without this patch and then tested the `s3 upload` command. The machine I was running on the the bucket I was uploading to were both in vapour-dev.

| File size | New version (with this patch) | Old version |
|-------------|-------------------------------------------|--------------|
| 1 Gig     | 0m12.539s     | 0m12.056s |
| 4 Gig     | 0m48.787s     | 0m44.785s |
| 16 Gig   | 3m14.435s     | 3m07.981s |
| 64 Gig   | 14m55.074s   | 13m25.082s |

Seems the new version is about 10% slower  than the older version. Is it worth fiddling with the parallelism to see if I can get that down?

**Comment by tmcgilchrist** [comment]
Seems like it would be worth some fiddling. 🌮

**Comment by erikd-ambiata** [comment]
Testing 5 parallel threads vs 100:

| File size  | 5 upload threads | 100 upload threads |
|---------------|------------------------|-----------------------------|
| 1 Gig       |   0m12.539s       |   0m12.056s            |
| 4 Gig       |   0m48.787s       |   0m44.785s            |
| 16 Gig     |   3m14.435s       |   3m07.981s            |
| 64 Gig     | 14m55.074s       | 13m25.082s            |

Testing 10 parallel threads vs 100:

| File size  | 10 upload threads | 100 upload threads |
|------------|-------------------|--------------------|
|  1G        |  0m12.240s        |   0m12.084s        |
|  4G        |  0m46.692s        |   0m44.975s        |
| 16G        |  3m10.022s        |   3m11.049s        |
| 32G        |  7m24.359s        |   6m49.902s        |
| 64G        | 14m29.903s        |  13m33.535s        |

Testing 20 parallel threads vs 100:

| File size  | 20 upload threads | 100 upload threads |
|------------|-------------------|--------------------|
|  1G        |  0m12.134s        |   0m12.164s        |
|  4G        |  0m47.019s        |   0m47.404s        |
| 16G        |  3m08.250s        |   3m10.470s        |
| 32G        |  6m56.568s        |   6m44.198s        |
| 64G        | 13m54.017s        |  13m20.936s        |

With 20 parallel threads, the performance differences are very minor (about 5%) but using 5 times fewer threads should make things more reliable.

**Comment by nhibberd** [comment]
:+1: for 20

**Pull request merged**
