### PR TITLE
quickcheck bounds

### PR DESCRIPTION
**Pull request by domdere**
@nhibberd 

this worth doing?

### CODE REVIEW

**Comment by charleso** [comment]
I think so :+1: /cc @jystic

**Comment by jystic** [comment]
Yep :triangular_flag_on_post:

**Comment by jystic** [comment]
I think we should merge this (after rebase) or I can do something similar in the other PR I have up for widen bounds, up to you @domdere ?

Having extra topic/ branches up on mismi makes jenkins sad is all

**Comment by jystic** [comment]
Closing, I'm including this in my version bounds PR

**Pull request closed without merging**
