### PR TITLE
Remove legacy `Aws` modules

### PR DESCRIPTION
**Pull request by EduardSergeev**

### CODE REVIEW

**Comment by charleso** [comment]
smell of deleted code

**Comment by charleso** [comment]
:100:

**Comment by markhibberd** [comment]
:100:

**Comment by charleso** [comment]
We can remove the `CommandK` commands now too I'm pretty sure /cc @nhibberd

**Comment by charleso** [comment]
eg. `UploadK`, `DownloadK` etc...

**Comment by nhibberd** [comment]
Yeah we can, was just part of legacy having both aws and amazonka

**Comment by tmcgilchrist** [comment]
Beautiful :rainbow:

**Pull request merged**
