### PR TITLE
Introduce missing runAWSDefaultRegionT

### PR DESCRIPTION
**Pull request by charleso**
/cc @nhibberd As discussed

### CODE REVIEW

**Comment by nhibberd** [comment]
:+1:

**Comment by markhibberd** [comment]
@charleso This is a bit of a risky one - could probably go either way on it, but we would need to be _very_ vigilant that this never got called from a library. However, we shouldn't ever be defaulting to Sydney (except in tests), would like to start pushing really hard on this. This needs an error handler function or needs to return a maybe etc...

**Comment by EduardSergeev** [comment]
@markhibberd So the ideal behaviour is to check environment variable and if it isn't set to produce an error instead of defaulting to Sydney, I am getting it right?

**Comment by markhibberd** [comment]
@EduardSergeev For production code yes.. I talked to @charleso offline - I think his is the correct implementation for tests, but for production we want to stop making the Sydney assumption.

**Pull request merged**
